# Based on https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/.pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]
        require_serial: true
        args: [--config=pyproject.toml]
      - id: flake8
        name: flake8
        entry: uv run flake8
        language: system
        types: [python]
        require_serial: true
      - id: isort
        name: isort
        entry: uv run isort
        require_serial: true
        language: system
        types_or: [cython, pyi, python]
        args: [--settings-path=pyproject.toml, --profile=black]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: check-added-large-files
        exclude: '\.gitattributes|static/images/.*'
      - id: check-toml
        types: [toml]
      - id: check-yaml
        args: [--allow-multiple-documents]
        types: [yaml]
      - id: no-commit-to-branch
      - id: trailing-whitespace
        types: [text]
        stages: [pre-commit, pre-push, manual]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        types: [python]
        args: [--py310-plus]
